version: '3.6'
services:
  mongo:
    container_name: landing_mongo
    image: mongo:4
    restart: always
    volumes:
    - mongodb_vol:/data/db
    networks:
    - landing_services-tier
    ports:
    - 127.0.0.1:27017:27017

  node:
    container_name: landing_node
    restart: always
    depends_on:
    - mongo
    build:
      context: .
      dockerfile: Dockerfile
    networks:
    - landing_services-tier
    ports:
    - $GLS_SERVER_HOST:$GLS_SERVER_PORT:$GLS_SERVER_PORT
    environment:
    - GLS_SERVER_HOST
    - GLS_SERVER_PORT
    - GLS_MONGO_CONNECT

volumes:
  mongodb_vol:

networks:
  landing_services-tier:
